# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnO-g_y8x2JuUBgIiDK_6woa8hmTsM7W
"""

!pip install geojson
!pip install pymavlink

import json
import geojson
from pymavlink import mavutil

class DroneController:
    def __init__(self, connection_string):
        self.master = mavutil.mavlink_connection(connection_string)
        print("Соединение с MAVLink установлено")

    def send_command(self, command):
        self.master.mav.command_long_send(
            self.master.target_system,
            self.master.target_component,
            command['command'],
            0,
            command.get('param1', 0),
            command.get('param2', 0),
            command.get('param3', 0),
            command.get('param4', 0),
            command.get('param5', 0),
            command.get('param6', 0),
            command.get('param7', 0)
        )
        print(f"Команда {command['command']} отправлена")

    def process_geojson(self, geojson_data):
        if isinstance(geojson_data, dict):
          geojson_data = json.dumps(geojson_data)
        features = geojson.loads(geojson_data)['features']
        for feature in features:
            geometry = feature['geometry']
            properties = feature['properties']

            if geometry['type'] == 'Point':
                coordinates = geometry['coordinates']
                command = {
                    'command': mavutil.mavlink.MAV_CMD_NAV_WAYPOINT,
                    'param1': properties.get('param1', 0),
                    'param2': properties.get('param2', 0),
                    'param3': properties.get('param3', 0),
                    'param4': properties.get('param4', 0),
                    'param5': coordinates[0],  # Долгота
                    'param6': coordinates[1],  # Широта
                    'param7': properties.get('altitude', 0)  # Высота
                }
                self.send_command(command)

if __name__ == "__main__":
    connection_string = 'udp:127.0.0.1:14551'  # адрес подключения
    drone_controller = DroneController(connection_string)

    # GeoJSON данных
    geojson_data = {
        "type": "FeatureCollection",
        "features": [{
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [37.6173, 55.7558]},
                "properties": {
                    "param1": 0,
                    "param2": 0,
                    "altitude": 100}}]}


    drone_controller.process_geojson(geojson_data)